"""Constants used across the application."""

# Analysis constants
MIN_PRODUCT_INDICATORS = 3
MIN_PRODUCT_INDICATORS_WITH_URL_PATTERN = 2
MIN_TITLE_LENGTH = 5
MIN_DESCRIPTION_LENGTH = 10
PRODUCT_PAGE_TIMEOUT_MS = 10000
DYNAMIC_CONTENT_WAIT_MS = 1500

# Discovery constants
MAX_DISCOVERY_ATTEMPTS = 3
SCROLL_WAIT_MS = 1000
JAVASCRIPT_WAIT_MS = 2000

# Retry constants
MAX_SAVE_RETRIES = 3
EXPONENTIAL_BACKOFF_BASE = 2

# Shipping constants
MIN_SHIPPING_TEXT_LENGTH = 10
MAX_SHIPPING_TEXT_LENGTH = 500
MAX_SHIPPING_CORE_LINES = 5

# Scraper statuses
STATUS_SUCCESS = "success"
STATUS_FAILURE = "failure"
STATUS_BLOCKED = "blocked"
STATUS_SKIPPED = "skipped"

# Logging separators
LOG_SEPARATOR = "=" * 70
LOG_STEP_PREFIX = "STEP"
