apiVersion: v1
kind: ServiceAccount
metadata:
  name: scraper-sa
  namespace: scraper-microservices
  annotations:
    azure.workload.identity/client-id: "<IDENTITY_CLIENT_ID>"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: scraper-microservices
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "<IDENTITY_CLIENT_ID>"
    keyvaultName: "<KEY_VAULT_NAME>"
    cloudName: "AzurePublicCloud"
    tenantId: "<TENANT_ID>"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: kafka-bootstrap-servers
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: database-secret
    type: Opaque
    data:
    - objectName: db-password
      key: DB_PASSWORD
    - objectName: db-user
      key: DB_USER
    - objectName: db-name
      key: DB_NAME
  - secretName: api-secret
    type: Opaque
    data:
    - objectName: api-key
      key: API_KEY
  - secretName: kafka-secret
    type: Opaque
    data:
    - objectName: kafka-bootstrap-servers
      key: KAFKA_BOOTSTRAP_SERVERS
